// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "crud/internal/models"

type requestCrudCreate struct {
	Req models.UserRequest `json:"req,omitempty"`
}

type responseCrudCreate struct {
	Resp models.UserResponse `json:"resp,omitempty"`
}

// Formal exchange type, please do not delete.
type requestCrudGetUser struct{}

// Formal exchange type, please do not delete.
type responseCrudGetUser struct{}

// Formal exchange type, please do not delete.
type requestCrudGetUsers struct{}

// Formal exchange type, please do not delete.
type responseCrudGetUsers struct{}

// Formal exchange type, please do not delete.
type requestCrudUpdate struct{}

// Formal exchange type, please do not delete.
type responseCrudUpdate struct{}

// Formal exchange type, please do not delete.
type requestCrudDelete struct{}

// Formal exchange type, please do not delete.
type responseCrudDelete struct{}
