// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"crud/internal/interfaces"
	"crud/internal/models"
)

type CrudCreate func(ctx context.Context, req models.UserRequest) (resp models.UserResponse, err error)
type CrudGetUser func(ctx context.Context) (err error)
type CrudGetUsers func(ctx context.Context) (err error)
type CrudUpdate func(ctx context.Context) (err error)
type CrudDelete func(ctx context.Context) (err error)

type MiddlewareCrud func(next interfaces.Crud) interfaces.Crud

type MiddlewareCrudCreate func(next CrudCreate) CrudCreate
type MiddlewareCrudGetUser func(next CrudGetUser) CrudGetUser
type MiddlewareCrudGetUsers func(next CrudGetUsers) CrudGetUsers
type MiddlewareCrudUpdate func(next CrudUpdate) CrudUpdate
type MiddlewareCrudDelete func(next CrudDelete) CrudDelete
